const { Buffer } = require('buffer');

function cleanText(value) {
  return String(value || '').replace(/\u0000/g, ' ').replace(/[ \t]+/g, ' ').replace(/\n{3,}/g, '\n\n').trim();
}
function lines(text) { return cleanText(text).split(/\n+/).map(s => s.trim()).filter(Boolean); }
function uuid() { return 'p_' + Math.random().toString(36).slice(2) + Date.now().toString(36); }
const SKILLS=['User research','UX research','Interaction design','Visual design','Information architecture','Prototyping','Design systems','Service design','Content design','Accessibility','Motion design','Data visualisation','Product strategy','Design thinking','Facilitation','Storytelling','Stakeholder management','Leadership','Mentoring','Communication','Systems thinking','Project management','AI / ML','Generative AI','HTML / CSS','JavaScript','Figma','Sketch','Adobe Creative Suite','Usability testing'];
const SECTION_NAMES={experience:/^(experience|work experience|professional experience|employment|career|work history)$/i,education:/^(education|academic background|qualifications)$/i,skills:/^(skills|core skills|expertise|competencies|tools|technical skills)$/i,projects:/^(projects|selected projects|selected work|case studies|portfolio)$/i,certifications:/^(certifications|certificates|training)$/i,awards:/^(awards|recognition|achievements)$/i,publications:/^(publications|speaking|talks)$/i};
function classifySection(s){for(const [k,re] of Object.entries(SECTION_NAMES))if(re.test(s.trim()))return k;return null;}
function parseDatePair(text){const re=/((?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)?\s*20\d{2})\s*(?:-|–|—|to)\s*((?:Present|Current|Now)|(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?)?\s*20\d{2})/i;const m=text.match(re);return m?{startDate:m[1].trim(),endDate:m[2].trim()}:null;}
function looksLikeDate(line){return /\b20\d{2}\b/.test(line)&&/(?:-|–|—|to|present|current|now)/i.test(line);}
function extractSections(text){const ls=lines(text),sections={header:[],experience:[],education:[],skills:[],projects:[],certifications:[],awards:[],publications:[],other:[]};let current='header';for(const line of ls){const section=classifySection(line.replace(/[:|]+$/,''));if(section){current=section;continue;}sections[current].push(line);}return sections;}
function extractContact(header){const joined=header.join(' '),email=(joined.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'',urls=[...joined.matchAll(/https?:\/\/[^\s,)]+/gi)].map(m=>m[0].replace(/[.)]+$/,'')),phone=(joined.match(/(?:\+?\d[\d\s().-]{7,}\d)/)||[])[0]||'',name=header.find(x=>!/@/.test(x)&&!/https?:\/\//i.test(x)&&!looksLikeDate(x)&&!/^(?:\+?\d[\d\s().-]+)$/.test(x)&&x.length<70)||'';return{name,email,phone,urls};}
function extractExperience(section){
  const out=[];
  const short=x=>x&&x.length>=2&&x.length<=90&&!/[.!?]$/.test(x)&&!/^[-•*]/.test(x);
  for(let i=0;i<section.length;i++){
    const line=section[i],date=parseDatePair(line);
    if(!date) continue;
    const before=line.replace(date.startDate,'').replace(date.endDate,'').replace(/[-–—|•]/g,' ').trim();
    const prevs=section.slice(Math.max(0,i-3),i).filter(x=>!looksLikeDate(x)&&!classifySection(x)&&x.length<140);
    const nexts=section.slice(i+1,Math.min(section.length,i+5)).filter(x=>!looksLikeDate(x)&&!classifySection(x));
    let role=before;
    if(!role||role.length<3||/^\d+$/.test(role)){
      const candidates=[...prevs.slice(-2).reverse(),...nexts.slice(0,2)].filter(short);
      role=candidates[0]||'Role';
    }
    const companyCandidates=[...prevs.slice(-2).reverse(),...nexts.slice(0,3)].filter(x=>short(x)&&x!==role);
    const company=companyCandidates.find(x=>/\b(inc|ltd|llc|corp|corporation|company|technologies|technology|systems|labs?|group|studio|agency|sap|ibm|microsoft|google|adobe|accenture|deloitte|tcs|infosys|wipro|capgemini)\b/i.test(x))||companyCandidates[0]||'';
    const desc=[];
    for(let j=i+1;j<Math.min(section.length,i+10);j++){
      if(parseDatePair(section[j])) break;
      if(section[j].length>30) desc.push(section[j]);
    }
    out.push({id:uuid(),role:role.slice(0,120),company:company===role?'':company.slice(0,120),...date,description:desc.slice(0,6).join(' '),responsibilities:desc.slice(0,6),achievements:[],confirmed:false,source:'resume'});
  }
  const seen=new Set();
  return out.filter(x=>{const k=[x.role,x.company,x.startDate,x.endDate].join('|').toLowerCase();if(seen.has(k))return false;seen.add(k);return true;});
}
function extractSkills(sections,text){const found=new Set(),skillText=[...sections.skills,...sections.header].join(' ').toLowerCase();for(const skill of SKILLS){const aliases=[skill.toLowerCase()];if(skill==='Generative AI')aliases.push('gen ai','generative artificial intelligence');if(skill==='AI / ML')aliases.push('artificial intelligence','machine learning');if(skill==='Visual design')aliases.push('visual ui','ui design');if(skill==='Interaction design')aliases.push('interaction');if(skill==='User research')aliases.push('ux research');if(skill==='Design systems')aliases.push('design system');if(aliases.some(a=>skillText.includes(a)))found.add(skill);}const all=text.toLowerCase();for(const skill of SKILLS){const aliases=[skill.toLowerCase()];if(skill==='Generative AI')aliases.push('gen ai');if(skill==='AI / ML')aliases.push('artificial intelligence','machine learning');const hits=aliases.reduce((n,a)=>n+(all.match(new RegExp(a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'))||[]).length,0);if(hits>=2)found.add(skill);}return[...found];}
function extractEducation(section){return section.filter(x=>/(university|college|institute|school|academy|bachelor|master|b\.tech|m\.tech|mba|mfa|bfa|phd|degree|diploma)/i.test(x)).slice(0,12).map(line=>({institution:line,degree:'',year:(line.match(/\b20\d{2}\b/)||[])[0]||''}));}
function buildProjects(sections,timeline){
  const sources=[...sections.projects,...sections.experience];
  const projectish=sources.filter(x=>/(redesign|designed|built|launched|led|created|developed|implemented|platform|product|app|website|system|dashboard|service|experience|initiative|program|project|client|customer|strategy|research|design)/i.test(x));
  const chunks=[];
  for(let i=0;i<projectish.length;i+=2){const chunk=projectish.slice(i,i+2).join(' ');if(chunk.length>45)chunks.push(chunk);}
  const escRe=x=>x.replace(/[.*+?^{}()|[\]\\]/g,'\\$&');
  const explicit=chunks.slice(0,40).map(chunk=>{
    const name=(chunk.match(/(?:project|product|platform|initiative|program|redesign|experience|dashboard|system)[:\\s-]+([^.;]{4,100})/i)||[])[1]||chunk.split(/[.!?]/)[0].slice(0,90);
    const skills=SKILLS.filter(s=>new RegExp(escRe(s),'i').test(chunk));
    const related=timeline.find(t=>t.company&&chunk.toLowerCase().includes(t.company.toLowerCase()));
    return{id:uuid(),name:name.trim(),company:related?.company||'',year:(chunk.match(/\\b20\\d{2}\\b/)||[])[0]||related?.startDate||'',startDate:related?.startDate||'',endDate:related?.endDate||'',client:'',industry:'',platform:'',deviceType:'',businessModel:'',audience:'',summary:chunk.slice(0,900),expectation:'',outcome:'',impact:'',skills,tools:[],methods:[],evidence:[chunk],source:'resume'};
  });
  if(explicit.length) return explicit;
  return timeline.map(t=>({id:uuid(),name:(t.role||'Career evidence')+(t.company?' at '+t.company:''),company:t.company||'',year:(t.startDate||'').match(/20\d{2}/)?.[0]||'',startDate:t.startDate||'',endDate:t.endDate||'',client:'',industry:'',platform:'',deviceType:'',businessModel:'',audience:'',summary:t.description||'',expectation:'',outcome:'',impact:'',skills:SKILLS.filter(s=>new RegExp(escRe(s),'i').test(t.description||'')),tools:[],methods:[],evidence:t.responsibilities||[],source:'resume'}));
}
function deterministic(text,filename){const sections=extractSections(text),contact=extractContact(sections.header),timeline=extractExperience(sections.experience),skills=extractSkills(sections,text),education=extractEducation(sections.education),projects=buildProjects(sections,timeline);return{schemaVersion:'lakshya.career.v2',source:{filename,processedAt:new Date().toISOString(),parser:'wing-span-inspired server parser',characterCount:text.length},person:contact,rawText:text,sections,timeline,projects,skills,education,certifications:sections.certifications,awards:sections.awards,publications:sections.publications,signals:{careerStageSignals:timeline.map(t=>t.role).filter(Boolean),geographySignals:[],evidenceQuality:text.length>12000?'rich':text.length>5000?'moderate':'sparse'}};}
async function parseBuffer(buffer,filename){const ext=(filename.split('.').pop()||'').toLowerCase();if(ext==='txt'||ext==='md'||ext==='csv')return buffer.toString('utf8');if(ext==='docx'){const mammoth=require('mammoth');return(await mammoth.extractRawText({buffer})).value;}if(ext==='xlsx'||ext==='xls'){const XLSX=require('xlsx'),wb=XLSX.read(buffer,{type:'buffer'});return wb.SheetNames.map(n=>'--- Sheet: '+n+' ---\n'+XLSX.utils.sheet_to_csv(wb.Sheets[n])).join('\n');}if(ext==='pdf'){const{extractText}=await import('unpdf');const result=await extractText(new Uint8Array(buffer),{mergePages:true});return Array.isArray(result.text)?result.text.join('\n'):result.text||'';}throw new Error('Unsupported file type: '+ext);}
async function aiEnrich(db){const key=process.env.GEMINI_API_KEY||process.env.OPENROUTER_API_KEY;if(!key)return{...db,analysisMode:'structured-parser'};const isOpenRouter=!!process.env.OPENROUTER_API_KEY&&!process.env.GEMINI_API_KEY;const prompt='You are the extraction engine for Lakshya Career Evidence Lab. Transform the supplied resume extraction into a comprehensive structured career database. Do not invent facts. Preserve every factual item from rawText and sections. Identify every distinct role, company, project, product, client, initiative, date, education item, certification, award, publication, skill, tool, method, domain, industry, platform and measurable outcome. Unknown values must be empty. Return ONLY JSON with person, timeline, projects, skills, education, certifications, awards, publications, domains, industries, tools, rawText, sections, signals. timeline entries need id, role, company, startDate, endDate, description, responsibilities, achievements, location, employmentType. projects need id,name,company,year,startDate,endDate,client,industry,platform,deviceType,businessModel,audience,summary,expectation,outcome,impact,skills,tools,methods,evidence. skills need name,type,evidence,frequency,confidence.\n\nSOURCE DATABASE:\n'+JSON.stringify(db);let url,body;if(isOpenRouter){url='https://openrouter.ai/api/v1/chat/completions';body={model:'openai/gpt-oss-120b',temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:'Return only valid JSON.'},{role:'user',content:prompt}]};}else{url='https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key='+encodeURIComponent(key);body={generationConfig:{temperature:0,responseMimeType:'application/json'},contents:[{role:'user',parts:[{text:prompt}]}]};}const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok)throw new Error('AI enrichment failed: '+res.status);const j=await res.json(),content=isOpenRouter?j.choices?.[0]?.message?.content:j.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('');if(!content)throw new Error('AI enrichment returned no content');return{...db,...JSON.parse(String(content).replace(/^```json\s*/,'').replace(/```$/,'').trim()),analysisMode:isOpenRouter?'ai-openrouter':'ai-gemini',rawText:db.rawText};}
module.exports=async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});try{const{filename,base64,rawText}=req.body||{};if(!filename&&!rawText)return res.status(400).json({error:'No document supplied'});const text=rawText||await parseBuffer(Buffer.from(base64,'base64'),filename);if(cleanText(text).length<80)return res.status(422).json({error:'The document was read, but there is not enough text to analyse. This usually means the PDF is scanned/image-only.'});const db=deterministic(text,filename||'pasted-text');const enriched=await aiEnrich(db);return res.status(200).json(enriched);}catch(e){console.error('Lakshya extraction error',e);return res.status(500).json({error:e?.message||'Extraction failed'});}};
